# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f313648569c1369a49c87e126f87b118ecf6a4ad76b4348b3dee1fa4870d536c43eebd1f6824a7201d2b4bcbaf212efe85f3aacfd20c7b2a328a7bd7a7d84ba4

test:
  secret_key_base: b2b89f16e36d61d27cefc5d6622a4d480313ac185dfc2461744f912e165f52904cdd914c08ce4024a6f8e479d39a57d808789152ed3fe52af5d66e29b351092a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
